// SqlGetTypeInfo provides information about native types supported by datasource.
//   Table Columns :
//   SqlTypeName :    TextValue (not null)   Native data-type name; for example, "CHAR()", "VARCHAR()", "MONEY", "LONG VARBINARY", or "CHAR ( ) FOR BIT DATA"
//   Type :           Type (not null)        Equivalent M Type
//   ColumnSize:      Number                 The maximum column size that the server supports for this data type. For numeric data, this is the maximum precision. For string data, this is the
//                                           length in characters. For datetime data types, this is the length in characters of the string representation (assuming the maximum allowed precision of the fractional
//                                           seconds component). NULL is returned for data types where column size is not applicable. For interval data types, this is the number of characters in the character
//                                           representation of the interval literal
//   GetLiteral:      FunctionValue          This function returns the literal representation of a value for a given type according to this data source
//   SEARCHABLE:      Number                 How the data type is used in a WHERE clause:
//                                            0 --->  if the column cannot be used in a WHERE clause.
//                                            1 --->  if the column can be used in a WHERE clause, but only with the LIKE predicate.
//                                            2 --->  if the column can be used in a WHERE clause with all the comparison operators except LIKE (comparison, quantified comparison, BETWEEN, DISTINCT, IN, MATCH, and UNIQUE).
//                                            3 --->  if the column can be used in a WHERE clause with any comparison operator.
//   UnsignedAttribute Number                Whether the data type is unsigned:
//                                            0 --->  if the data type is signed.
//                                            1 --->  if the data type is unsigned.
//                                            null ---> if the attribute is not applicable to the data type or the data type is not numeric.
//   NumericPrecisionRadix Number            If the data type is an approximate numeric type, this column contains the value 2, indicating that COLUMN_SIZE specifies a number of bits.
//                                           For exact numeric types, this column contains the value 10, indicating that COLUMN_SIZE specifies a number of decimal digits. Otherwise, this column is NULL.
let
    GetNumberLiteral = (value as number) => Number.ToText(value),
    GetTimeLiteral = (value as time) => Time.ToText(value, [Format = "HH:mm:ss.FFFFFFF"]),
    GetDateLiteral = (value as date) => Date.ToText(value, [Format = "yyyy-MM-dd"]),
    GetDateTimeLiteral = (value as datetime) as text =>
        DateTime.ToText(value, [Format = "yyyy-MM-dd HH:mm:ss.FFFFFFF"]),
    GetStringLiteral = (value as text) as text => Text.Format("#{0}#{1}#{2}", {"'", value, "'"}),
    // Types below represent the most common types supported by Spice, full list can be found at: https://github.com/spiceai/spiceai/pull/6259/files#diff-f54094c62d6711d2ad54d367025e2a0be85bba0e005a6496bf851c20d1126c50R150
    TypeInfo = Table.FromRecords(
        {
            [
                Name = "BOOLEAN",
                SqlType = -7,
                Type = Logical.Type,
                Unsigned = false,
                ColumnSize = 1,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = null,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "SMALLINT",
                SqlType = 5,
                Type = Int16.Type,
                Unsigned = false,
                ColumnSize = 5,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "INTEGER",
                SqlType = 4,
                Type = Int32.Type,
                Unsigned = false,
                ColumnSize = 10,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "BIGINT",
                SqlType = -5,
                Type = Int64.Type,
                Unsigned = false,
                ColumnSize = 19,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "REAL",
                SqlType = 7,
                Type = Single.Type,
                Unsigned = false,
                ColumnSize = 24,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "DOUBLE",
                SqlType = 8,
                Type = Double.Type,
                Unsigned = false,
                ColumnSize = 53,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 2,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "DECIMAL",
                SqlType = 2,
                Type = Decimal.Type,
                Unsigned = false,
                ColumnSize = 38,
                GetLiteral = GetNumberLiteral,
                Searchable = 2,
                NumberPrecisionRadix = 10,
                LiteralPrefix = null,
                LiteralSuffix = null
            ],
            [
                Name = "DATE",
                SqlType = 91,
                Type = Date.Type,
                Unsigned = false,
                ColumnSize = 10,
                GetLiteral = GetDateLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "TIME",
                SqlType = 92,
                Type = Time.Type,
                Unsigned = false,
                ColumnSize = 15,
                GetLiteral = GetTimeLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "TIMESTAMP",
                SqlType = 93,
                Type = DateTime.Type,
                Unsigned = false,
                ColumnSize = 26,
                GetLiteral = GetDateTimeLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "VARCHAR",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = GetStringLiteral,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "INTERVAL",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = null,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "ARRAY",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = null,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ],
            [
                Name = "STRUCT",
                SqlType = 12,
                Type = Text.Type,
                Unsigned = false,
                ColumnSize = 16384,
                GetLiteral = null,
                Searchable = 3,
                NumberPrecisionRadix = null,
                LiteralPrefix = "'",
                LiteralSuffix = "'"
            ]
        }
    )

in
    TypeInfo
